### ISSUE TITLE
When on desktop, include "institution" and "service" labels on the left of their respective dropdowns

### ISSUE THREAD

**Issue by georgeslabreche** [assemblio/citizen-satisfaction#21]
**ACCEPTANCE CRITERIA**
- [x] Don't display labels when on tablet/mobile view.
- [x] Language switching works.
- [x] Same gray color as other labels.

![cs_layout preview 4](https://cloud.githubusercontent.com/assets/1258236/22117395/187d00e8-de74-11e6-98b8-d06656884284.png)

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa you did not fulfill acceptance criteria.

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa why did you put this back to QA? You still did not fulfill acceptance criteria.

**Comment by dafinaolluri** [comment]
**Translation Provided**

- [ ] English: Institution, Service

- [ ] Serbian: Institucije, Usluge

@diamanthaxhimusa
