### ISSUE TITLE
Images not showing..

### ISSUE THREAD

**Issue by partini** [assemblio/citizen-satisfaction#36]
For some reason there is an extra "/inactive" in the image source and images are not found.
See screenshot:
![screen shot 2017-01-26 at 4 08 51 pm](https://cloud.githubusercontent.com/assets/7932995/22336297/fb5d1818-e3e1-11e6-9897-9f60e46d9fac.png)

**Comment by diamanthaxhimusa** [comment]
@partini  I fixed it !!
