### ISSUE TITLE
Missing social media meta tags and images (Twitter and Facebook)

### ISSUE THREAD

**Issue by georgeslabreche** [assemblio/citizen-satisfaction#5]
Need to implement script that changes title and description language depending on selected language.

Use the standard template in section 2:
https://moz.com/blog/meta-data-templates-123

Test this work with Facebook sharing debugger:
https://developers.facebook.com/tools/debug/sharing/

Facebook share image:
![fb_share](https://cloud.githubusercontent.com/assets/1258236/22030061/cbb49eee-dcdc-11e6-9577-e5be24700799.png)

Twitter share image:
![tw_share 1024x512](https://cloud.githubusercontent.com/assets/1258236/22030072/d260998c-dcdc-11e6-9925-e46a5fb1efb2.png)

**Comment by diamanthaxhimusa** [comment]
should we add this in other languages rather than just in albanian ?

**Comment by georgeslabreche** [comment]
@dafinaolluri @diamanthaxhimusa if the language switching works for this, then we will have to ask the designer to provide us English and Serbian version of the images. We would have to give him the translations.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche    we need to  disccuss more about what text do we put inside meta tags , we need authors m creators etc.

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa if you have questions that need to be answered before you can finish an issue then please label the issue with the "question" label and leave it In Progress. Do not move it to Review/QA. Review/QA is only for tasks you think you are finished.

Use the following meta values

**For Facebook:**

- og:type = "website"

**For Twitter:**

- twitter:card = "summary"
- twitter:site = "@map_rks"
- twitter:creator = "@OpenDataKosovo"

For site_name and title, use the same value as title in i18n.js
For description, use the same value as description in i18n.js

**IMPORTANT:**
As suggested by Partin, the jQuery approach may not work, you might have to try this instead:
http://stackoverflow.com/a/10157637/4030804

Or maybe use document.write like in this example at the bottom:
http://stackoverflow.com/a/2568915/4030804

**Comment by partini** [comment]
@diamanthaxhimusa Use this link to test if the twitter is scraping data correctly: https://cards-dev.twitter.com/validator
