### ISSUE TITLE
Trends chart is not mobile friendly

### ISSUE THREAD

**Issue by georgeslabreche** [assemblio/citizen-satisfaction#55]
Maybe just remove the y axis labels when on mobile?
You can probably achieve this with CSS but just so you know the official javascript option to remove the y axis lable is this one:
http://api.highcharts.com/highcharts/yAxis.labels.enabled

**On iPhone 5:**
<img width="302" alt="screen shot 2017-02-16 at 10 46 20 am" src="https://cloud.githubusercontent.com/assets/1258236/23016003/3bafe400-f435-11e6-9e83-6b6036c67216.png">

**Comment by diamanthaxhimusa** [comment]
![selection_081](https://cloud.githubusercontent.com/assets/16455067/23028874/f05a62b2-f468-11e6-97d1-5ceb65069f02.png)

@georgeslabreche  can you recheck please? its working for me.

**Comment by dafinaolluri** [comment]
@georgeslabreche can you test it again?

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa are you sure you committed all the code?

<img width="368" alt="screen shot 2017-02-20 at 7 02 14 pm" src="https://cloud.githubusercontent.com/assets/1258236/23136891/32d4c87e-f79f-11e6-94e3-b3f7ed50b882.png">
