### ISSUE TITLE
Include Turkish translation

### ISSUE THREAD

**Issue by dafinaolluri** [assemblio/citizen-satisfaction#56]
**Acceptance Criteria**

- [ ] Title
- [ ] Description
- [ ] Description Bottom
- [ ] Institution Label
- [ ] Service Label
- [ ] Logotext1
- [ ] Logotext2
- [ ] Institutions
- [ ] Services
- [ ] Answers
- [ ] Satisfied'
- [ ] Moderately Satisfied	
- [ ] Dissatisfied	
- [ ] quality of service	
- [ ] behaviour of the official	
- [ ]  timeliness of the service 	
- [ ] payment level of the service	
- [ ] no online	
- [ ] Ranking
- [ ] Visualizer	
- [ ] show services	
- [ ] hide services
- [ ] Search for...'

**Comment by diamanthaxhimusa** [comment]
@dafinaolluri @georgeslabreche  we need Json data to be in turkish aswell.

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa, you are referring to JSON we are receiving from AppDec, right?

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche yes.

**Comment by georgeslabreche** [comment]
This is not done, please be more careful when testing your own code:

**x axis labels**
<img width="735" alt="screen shot 2017-02-20 at 7 03 53 pm" src="https://cloud.githubusercontent.com/assets/1258236/23136981/b6ba9a1a-f79f-11e6-80dc-e49af75c294d.png">

**All Services**
<img width="343" alt="screen shot 2017-02-20 at 7 04 02 pm" src="https://cloud.githubusercontent.com/assets/1258236/23136982/b6bba0f4-f79f-11e6-9239-716b99c2ea49.png">

**Alignmnent not good in turkish. Please insert blank new line for other indicator labels**
<img width="676" alt="screen shot 2017-02-20 at 7 04 25 pm" src="https://cloud.githubusercontent.com/assets/1258236/23136983/b6be4714-f79f-11e6-80b2-d3415e854473.png">


<img width="647" alt="screen shot 2017-02-20 at 7 04 29 pm" src="https://cloud.githubusercontent.com/assets/1258236/23136984/b6bed058-f79f-11e6-9824-7fd28015b47f.png">
