### ISSUE TITLE
Link to AppDec API using https.

### ISSUE THREAD

**Issue by georgeslabreche** [assemblio/citizen-satisfaction#6]
Update the API URL used to the production HTTP**S** URL:
https://opi.rks-gov.net/api/report/general

**Comment by dafinaolluri** [comment]
@georgeslabreche We need more infos about this task.

**Comment by georgeslabreche** [comment]
@dafinaolluri I added more info. I am also flagging this task as a major risk because we cannot deliver a final product without the required link working beforehand (i.e. https://opi.rks-gov.net/api/report/general). You should raise this with the client.

**Comment by georgeslabreche** [comment]
@dafinaolluri oh yay, they fixed it!
