### ISSUE TITLE
When on tablet/mobile, we can't click on the satisfaction level drop down. Clicking on it does nothing.

### ISSUE THREAD

**Issue by georgeslabreche** [assemblio/citizen-satisfaction#60]
<img width="705" alt="screen shot 2017-02-20 at 7 09 55 pm" src="https://cloud.githubusercontent.com/assets/1258236/23137077/489f6fb4-f7a0-11e6-985c-0514170c7af2.png">

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche are you sure you tested it properly, it works just fine on my phone. Can you please test this again? thanks.
