### ISSUE TITLE
Make sure Serbian translation is showing everywhere.

### ISSUE THREAD

**Issue by georgeslabreche** [assemblio/citizen-satisfaction#9]
**MISSING SERBIAN TEXT**
- [x] Institutions
- [x] Services
- [x] Answers
- [x] Citizens
- [x] Satisfied
- [x] Moderately satisfied
- [x] Dissatisfied
- [x] Friendliness of the official
- [x] Ranking (Niveli vleresues)
- [x] Visualizer

**Comment by dafinaolluri** [comment]
**SERBIAN TRANSLATION**

- [x] Institucija
- [x] Usluga
- [x] Odgovor
- [x] Građanin
- [x] Zadovoljan
- [x] Umereno zadovoljan
- [x] Nezadovoljan
- [x] Ljubaznost funkcionera
- [x] Rangiranje (Nivo procene)
- [x] Vizualizator
